# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :tests do
  	run_tests(
	  scheme: "Discussion-Korea",
	  slack_url: "https://hooks.slack.com/services/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"
	)
  end
  lane :beta do
    increment_build_number(xcodeproj: "Discussion-Korea.xcodeproj")
    build_app(scheme: "Discussion-Korea")
    upload_to_testflight
	slack(
		message: "Testflight 배포에 성공했습니다!",
		slack_url: "https://hooks.slack.com/services/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",
	)
  end
  error do |lane, exception, options|
  	slack(
		message: "에러 발생 : #{exception}",
		success: false,
		slack_url: "https://hooks.slack.com/services/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",
	)
  end
end
